---
- name: Deploy NGINX Ingress using Helm
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Vérifier si la release NGINX Ingress existe
      shell: helm list --all-namespaces | grep my-nginx-ingress
      register: nginx_release
      ignore_errors: yes

    - name: Sauvegarder le manifeste de l'ancienne release NGINX Ingress
      shell: kubectl get deployment my-nginx-ingress-deployment -n ingress-nginx -o yaml > /Users/salim/Documents/ansible/manifest-backup.yaml
      when: nginx_release.rc == 0
      delegate_to: localhost

    - name: Installer ou mettre à jour NGINX Ingress Controller
      shell: helm upgrade --install my-nginx-ingress /Users/salim/Documents/ansible/my-nginx-ingress -f /Users/salim/Documents/ansible/my-nginx-ingress/values.yaml -n ingress-nginx
      delegate_to: localhost
