apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-ingress-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-nginx-ingress
  template:
    metadata:
      labels:
        app: my-nginx-ingress
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80